@startuml
actor User
rectangle ManageQuestion{
    User -right- (ManageQuestion)
    (ManageQuestion) .- (CreateQuestion) : <<extends>>
    (ManageQuestion) .- (EditQuestion) : <<extends>>
    (ManageQuestion) .- (ViewQuestion) : <<extends>>
    (ManageQuestion) .- (DeleteQuestion) : <<extends>>
    (ManageQuestion) .- (FollowQuestion) : <<extends>>
}
@enduml
