export const GET_ALL_QUETIONS = "GET_ALL_QUETIONS";
export const ADD_NEW_QUESTION = "ADD_NEW_QUESTION";
export const GET_QUESTION = "GET_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";

export const VOTE_QUESTION = "VOTE_QUESTION";
export const UNVOTE_QUESTION = "UNVOTE_QUESTION";

export const CHECK_VOTE_QUESTION = "CHECK_VOTE_QUESTION";
export const CHECK_UNVOTE_QUESTION = "CHECK_UNVOTE_QUESTION";

export const UPDATE_VIEW_QUESTION = "UPDATE_VIEW_QUESTION";

export const GET_ALL_COMMENTS_QUESTION = "GET_ALL_COMMENTS_QUESTION";
export const ADD_NEW_COMMENT_QUESTION = "ADD_NEW_COMMENT_QUESTION";
export const UPDATE_COMMENT_QUESTION = "UPDATE_COMMENT_QUESTION";
export const DELETE_COMMENT = "DELETE_COMMENT_QUESTION";

export const VOTE_COMMENT = "VOTE_COMMENT";
export const UNVOTE_COMMENT = "UNVOTE_COMMENT";

export const CHECK_VOTE_COMMENT = "CHECK_VOTE_COMMENT";

export const GET_ALL_REPLIES_COMMENT = "GET_ALL_REPLIES_COMMENT";
export const ADD_NEW_REPLY_COMMENT_QUESTION = "ADD_NEW_REPLY_COMMENT_QUESTION";
export const CHECK_REPLY = "CHECK_REPLY";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORY_QUESTION = "GET_CATEGORY_QUESTION";

export const GET_ALL_QUESTIONS_CATEGORY = "GET_ALL_QUESTIONS_CATEGORY";

export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const ADD_NEW_TAGS = "ADD_NEW_TAGS";

export const GET_ALL_QUESTIONS_TAG = "GET_ALL_QUESTIONS_TAG";

export const CREATE_USER = "CREATE_USER";
export const SIGN_IN = "SIGN_IN";
export const LOG_OUT = "LOG_OUT";

export const GET_USER = "GET_USER";
export const GET_USER_OTHER = "GET_USER_OTHER";