version: '3'
volumes:
  mongo_data:

services:
  backup-db:
    image: alpine
    stdin_open: true
    tty: true
    logging:
        driver: none
    volumes:
        - mongo_data:/volume/mongo_data
    command: ["tar", "-C", "/volume", "--exclude='logs/*'", "-cjf", "-", "./"]
    container_name: mongo_data_backup

  restore-db:
    image: alpine
    stdin_open: true
    tty: true
    volumes:
        - mongo_data:/volume/mongo_data
    command: ["tar", "-C", "/volume", "-xj"]
    container_name: mongo_data_backup
