version: "2"
volumes:
  mongo_data:

services:
    # app_db:
    #     image: mongo
    #     volumes:
    #         - mongo_data:/data/db
    #     ports:
    #         - "27017:27017"

    # remmember replace the volume path
    app_srv:
        build: .
        volumes:
            - path/server:/app/server
        ports:
            - 8080:5000