version: "3"
volumes:
  mongo_data:

services:
    # app_db:
    #     image: mongo
    #     volumes:
    #         - mongo_data:/data/db
    #     ports:
    #         - "27017:27017"

    app_srv:
        build: .
        volumes:
            - /Users/nguyenphu/Desktop/document/gitlab/project-web-thuc-tap-cong-nhan/server:/app/server
        ports:
            - 8080:5000