@startuml class_diagrame
class User {
    userID: string
    fullname: string
    avatar: string
    categories: list
    tags: list
    follow: list
    votes: int
    unvotes: int
    password: string
    email: emailtype
    username: string
    saveQuestions: list
}

class Question {
    questionID: string
    title: string
    summaryContent: string
    content: text
    image: listobject
    topComment: JsonString
    categoryID: string
    userID: User
    tags: listTag
    votes: int
    unvotes: int
    views: int
    comments: int
    userFollows: listUser
}

class Comment {
    commentID: string
    userID: User
    questionID: Question
    content: JsonString
    images: listJsonString
    votes: int
    unvotes: int
    replies: listJsonString
}

class Categery {
    categoryID: string
    name: string
    userFollows: listUser
}

class Tag {
    id: string
    text: string
    tagID: string
    userFollows: listUser
}

class Notification {
    notificationID: string
    senderID: User
    receiverID: User
    questionID: Question
    commentID: Comment
    message: string
}

class Mark {
    _id: objectID
    userId: User
    questionId: Question
    time: datetime
}

class Follow {
    _id: objectID
    userId: User
    questionId: Question
}

class VoteQuestion {
    userID: User
    questionID: Question
    voteID: string
}

class UnvoteQuestion {
    userID: User
    questionID: Question
    unvoteID: string
}

class VoteComment {
    userID: User
    questionID: Question
    voteID: string
    commentID: string
}

class UnvoteComment {
    userID: User
    questionID: Question
    unvoteID: string
    commentID: string
}

Account -down-> User 
Question -left-> User
Comment -left-> User
Comment -down-> Question
Question -down-> Categery
Question -down-> Tag
Notification -left-> User
Notification -left-> Question
Mark -left-> User
Mark -down-> Question
Follow -right-> User
Follow -> Question
VoteQuestion -left-> User
VoteQuestion -right-> Question
UnvoteQuestion -right-> User
UnvoteQuestion -right-> Question
VoteComment -right-> User
VoteComment -right-> Question
UnvoteComment -right-> User
UnvoteComment -right-> Question

@enduml