FEATURE
Schema

User system:
	Register user
		url: /register
		method: POST
		content-type: json

	Update user
		url: /user/
		method: PATCH
		content-type: json

Auth:
	Login
		url: /login
		method: POST
		content-type: json

	logout
		url: /logout
		method: GET
		content-type: json
			
Question:
	Get all question of user
		url: /user/<userID>/question
		method: GET
		content-type: json
		
	Get list question
		url: /questions
		method: GET
		content-type: json

	Get question item
		url: /questions/questionID
		method: GET
		content-type: json

	Create question
		url: /questions
		method: POST
		content-type: json

	Edit question
		url: /questions/questionID
		method: PATCH
		content-type: json]

	Delete question
		url: /questions/questionID
		method: DELETE

Comment:
	Get all comment of question
		url: /question/<questionID>/comments
		method: GET
		content-type: json

	Add comment to a question
		url: /comments
		method: POST
		content-type: json
		
	Remove a comment of a question
		url: /comment/<commentID>
		method: DELETE

	Edit a comment of a question
		url: /comment/<commentID>
		method: PATCH
		content-type: json


Category:
	Get list category
		url: /categories
		method: GET
		content-type: json

	Add category
		url: /categories
		method: POST
		content-type: json
		
	Remove a category
		url: /categories/<categoryID>
		method: DELETE

	Edit a category
		url: /categories/<categoryID>
		method: DELETE

Tag:
	Get list tag
		url: /tags
		method: GET
		content-type: json

	Add tag
		url: /tags
		method: POST
		content-type: json
		
	Remove a tags
		url: /tag/<tagID>
		method: DELETE

	Edit a tags
		url: /tag/tagID>
		method: DELETE

Notification:
	Get list notification
		url: /notifications
		method: GET
		content-type: json

	Add notification
		url: /notifications
		method: POST
		content-type: json
		
	Remove a notification
		url: /notifications/<notificationID>
		method: DELETE

	Edit a notification
		url: /notifications/notificationID>
		method: DELETE
