FEATURE
Schema

User system:
	Register user
		url: /register
		method: POST
		content-type: json

	Update user
		url: /user/
		method: PATCH
		content-type: json

Auth:
	Login
		url: /login
		method: POST
		content-type: json

	logout
		url: /logout
		method: GET
		content-type: json
			
Question:
	Get all question of user
		url: /user/<userId>/question
		method: GET
		content-type: json
		
	Get list question
		url: /question
		method: GET
		content-type: json

	Get question item
		url: /question/questionId
		method: GET
		content-type: json

	Create question
		url: /question
		method: POST
		content-type: json

	Edit question
		url: /question/questionId
		method: PATCH
		content-type: json

	Delete question
		url: /question/questionId
		method: DELETE

Comment:
	Get all comment of question
		url: /question/<questionId>/comment
		method: GET
		content-type: json

	Get list comment of a Question
		url: /question/<questionId>/comment
		method: GET
		content-type: json

	Add comment to a question
		url: /question/<questionId>/comment
		method: POST
		content-type: json
		
	Remove a comment of a question
		url: /question/<questionId>/comment/<commentId>
		method: DELETE

	Edit a comment of a question
		url: /question/<questionId>/comment/<commentId>
		method: DELETE

Category:
	Get list category
		url: /category
		method: GET
		content-type: json

	Add category
		url: /category
		method: POST
		content-type: json
		
	Remove a category
		url: /category/<category_id>
		method: DELETE

	Edit a category
		url: /category/<category_id>
		method: DELETE

Tag:
	Get list tag
		url: /tag
		method: GET
		content-type: json

	Add tag
		url: /tag
		method: POST
		content-type: json
		
	Remove a tag
		url: /tag/<tag_id>
		method: DELETE

	Edit a tag
		url: /tag/tag_id>
		method: DELETE

Notification:
	Get list notification
		url: /notification
		method: GET
		content-type: json

	Add notification
		url: /notification
		method: POST
		content-type: json
		
	Remove a notification
		url: /notification/<notification_id>
		method: DELETE

	Edit a notification
		url: /notification/notification_id>
		method: DELETE


